In [1]:
from google.colab import files
uploaded = files.upload()

Saving iris (2).xlsx to iris (2).xlsx


In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
data = pd.read_excel('iris (2).xlsx')

data.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [4]:
X = data.iloc[:, :-1]   # Features
y = data.iloc[:, -1]    # Target

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

In [6]:
rf = RandomForestClassifier(n_estimators=10, random_state=42)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy with 10 trees:", accuracy)

Accuracy with 10 trees: 1.0


In [7]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [8]:
best_score = 0
best_tree = 0

for trees in [5,10,20,50,100,150,200]:

    rf = RandomForestClassifier(n_estimators=trees, random_state=42)

    rf.fit(X_train, y_train)

    pred = rf.predict(X_test)

    score = accuracy_score(y_test, pred)

    print("Trees:", trees, " Accuracy:", score)

    if score > best_score:
        best_score = score
        best_tree = trees

print("\nBest Accuracy:", best_score)
print("Best Number of Trees:", best_tree)

Trees: 5  Accuracy: 1.0
Trees: 10  Accuracy: 1.0
Trees: 20  Accuracy: 1.0
Trees: 50  Accuracy: 1.0
Trees: 100  Accuracy: 1.0
Trees: 150  Accuracy: 1.0
Trees: 200  Accuracy: 1.0

Best Accuracy: 1.0
Best Number of Trees: 5


In [9]:
rf_best = RandomForestClassifier(n_estimators=best_tree, random_state=42)

rf_best.fit(X_train, y_train)

best_pred = rf_best.predict(X_test)

print("Confusion Matrix for Best Model:")
print(confusion_matrix(y_test, best_pred))

Confusion Matrix for Best Model:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
